# Generated by Django 5.1a1 on 2024-06-19 22:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('OBJECTID', models.AutoField(primary_key=True, serialize=False)),
                ('car_park_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
                ('maximum_stay', models.CharField(blank=True, max_length=50, null=True)),
                ('charges', models.CharField(blank=True, max_length=100, null=True)),
                ('electric_or_hydrogen_or_hybrid', models.CharField(blank=True, max_length=100, null=True)),
                ('petrol_vehicles_registered_from_2005', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_vehicles_registered_from_2015', models.CharField(blank=True, max_length=100, null=True)),
                ('other_vehicles', models.CharField(blank=True, max_length=100, null=True)),
                ('saturday_am_price', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('lot_type', models.CharField(choices=[('roadside', 'Roadside'), ('public', 'Public')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PublicParkingPricingModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('parking_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicParkingPricingModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('parking_name', models.CharField(max_length=100)),
                ('period_type', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicParkingPricingModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('parking_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicParkingPricingModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('parking_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
