# Generated by Django 5.1a1 on 2024-06-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='OBJECTID',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='publicparkingpricingmodel1',
            old_name='OBJECTID',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='publicparkingpricingmodel2',
            old_name='OBJECTID',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='publicparkingpricingmodel3',
            old_name='OBJECTID',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='publicparkingpricingmodel4',
            old_name='OBJECTID',
            new_name='objectid',
        ),
    ]
