# Generated by Django 5.0.6 on 2024-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_objectid_parkinglot_objectid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
